### PR TITLE
Contains treats to memory leaks

### PR DESCRIPTION
**Pull request by johnny5janbohac**
I have added treats to memory leaks, code now contains call to function FreeCredentialhandle(handle) if CtxHandle is not longer needed. I have also made CtxHandle globaly usable variable

### CODE REVIEW

**Comment by ibauersachs** [comment]
Hey, thanks for your contribution!
Would you mind cleaning this up a bit? Indents should be with spaces, no unnecessary whitespace changes, please remove your initials/date comments and the changes to the Apache location path.

**Comment by johnny5janbohac** [comment]
Do you mean Apache include paths and paths to libraries in mod_spnego.vcxproj ?

**Comment by ibauersachs** [comment]
> Do you mean Apache include paths and paths to libraries in mod_spnego.vcxproj ?

Yes, the C:\Apache2 vs. $(APACHE2DIR)

**Comment by johnny5janbohac** [comment]
It is done

**Pull request merged**
